site_name: Home Assistant Target Timeframes
repo_url: https://github.com/bottlecapdave/homeassistant-targettimeframes
docs_dir: _docs

nav:
  - Home: index.md
  - Setup:
    - ./setup/data_source.md
    - ./setup/target_timeframe.md
    - ./setup/rolling_target_timeframe.md
  - services.md
  - events.md
  - blueprints.md
  - faq.md
  - sponsorship.md

# extra:
#   version:
#     provider: mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: "#"

plugins:
  - search
  - git-authors:
      show_email_address: false

theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

strict: true

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn