blueprint:
  name: Target Time Period - Spin Wheel Of Fortune (single)
  description: Automatically spin the wheel of fortune when spins become available
  domain: automation
  author: BottlecapDave

  input:
    wheel_of_fortune_spins:
      name: "Wheel of fortune spins"
      description: "The sensor that holds the number wheel of fortune spins (e.g. sensor.target_time_periods_{{ACCOUNT_ID}}_wheel_of_fortune_spins_electricity)"
      selector:
        entity:
          filter:
            domain: sensor
            integration: target_time_periods

variables:
  wheel_of_fortune_spins: !input wheel_of_fortune_spins

mode: queued
max: 4
trigger:
  - platform: numeric_state
    entity_id: !input 'wheel_of_fortune_spins'
    above: 0
condition: []
action:
  - repeat:
      count: '{{ states(wheel_of_fortune_spins) | int }}'
      sequence:
        - service: target_time_periods.spin_wheel_of_fortune
          data: {}
          target:
            entity_id: !input 'wheel_of_fortune_spins'