import pytest

from custom_components.target_timeframes.entities import compare_config_to_attributes
from custom_components.target_timeframes.const import CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA, CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT, CONFIG_TARGET_HOURS, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT, CONFIG_TARGET_TYPE

@pytest.mark.asyncio
@pytest.mark.parametrize("attributes,expected_result",[
  (None, False),
  ({}, False),
  ({ CONFIG_TARGET_HOURS: 1, CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: False, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT }, False),
  ({ CONFIG_TARGET_HOURS: 2, CONFIG_TARGET_TYPE: "Continuous", CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: False, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT }, False),
  ({ CONFIG_TARGET_HOURS: 1, CONFIG_TARGET_TYPE: "Intermittent", CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: False, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT }, False),
  ({ CONFIG_TARGET_HOURS: 1, CONFIG_TARGET_TYPE: "Continuous", CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: True, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT }, False),
  ({ CONFIG_TARGET_HOURS: 1, CONFIG_TARGET_TYPE: "Continuous", CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: False, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT + 1 }, False),
  ({ CONFIG_TARGET_HOURS: 1, CONFIG_TARGET_TYPE: "Continuous", CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: False, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT }, True),
  ({ CONFIG_TARGET_HOURS: 1, CONFIG_TARGET_TYPE: "Continuous", "Something": "else", CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: False, CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT }, True),
])
async def test_when_config_is_compared_to_attributes_then_expected_value_is_returned(attributes, expected_result):
  current_config = {
    CONFIG_TARGET_HOURS: 1,
    CONFIG_TARGET_TYPE: "Continuous",
    CONFIG_TARGET_CALCULATE_WITH_INCOMPLETE_DATA: False,
    CONFIG_TARGET_MINIMUM_REQUIRED_MINUTES_IN_SLOT: CONFIG_TARGET_DEFAULT_MINIMUM_REQUIRED_MINUTES_IN_SLOT
  }

  actual_result = compare_config_to_attributes(current_config, attributes)
  assert actual_result == expected_result