blank_issues_enabled: false
contact_links:
  - name: Integration Support
    url: https://github.com/BottlecapDave/homeassistant-targettimeperiods/discussions
    about: Please ask and answer questions here.
