update_target_timeframe_config:
  name: Update target timeframe config
  description: Updates a given target timeframe's config.
  target:
    entity:
      integration: target_timeframes
      domain: binary_sensor
  fields:
    target_hours:
      name: Hours
      description: The optional number of hours the target timeframe sensor should come on during a 24 hour period.
      example: 1.5
      selector:
        number:
          step: any
          mode: box
    target_start_time:
      name: Start time
      description: The optional time the evaluation period should start.
      example: '06:00'
      selector:
        text:
    target_end_time:
      name: End time
      description: The optional time the evaluation period should end.
      example: '19:00'
      selector:
        text:
    target_offset:
      name: Offset
      description:
        The optional offset to apply to the target timeframe when it starts
      selector:
        text:
    target_minimum_value:
      name: Minimum value
      description:
        The optional minimum value the selected values should not go below
      example: 0.10
      selector:
        number:
          step: any
          mode: box
    target_maximum_value:
      name: Maximum value
      description:
        The optional maximum value the selected values should not go above
      example: 0.10
      selector:
        number:
          step: any
          mode: box
    target_weighting:
      name: Weighting
      description:
        The optional weighting that should be applied to the selected values
      example: '1,2,1'
      selector:
        text:
    persist_changes:
      name: Persist Changes
      description: Determines if the changes should be persisted to the original configuration or should be temporary and reset upon integration reload.
      selector:
        boolean:

update_rolling_target_timeframe_config:
  name: Update rolling target timeframe config
  description: Updates a given rolling target timeframe's config.
  target:
    entity:
      integration: target_timeframes
      domain: binary_sensor
  fields:
    target_hours:
      name: Hours
      description: The optional number of hours the target timeframe sensor should come on during a 24 hour period.
      example: 1.5
      selector:
        number:
          step: any
          mode: box
    target_look_ahead_hours:
      name: Look ahead hours
      description: The optional number of hours worth of values the sensor should look at for the evaluation period.
      example: 8.5
      selector:
        number:
          step: any
          mode: box
    target_offset:
      name: Offset
      description:
        The optional offset to apply to the target timeframe when it starts
      selector:
        text:
    target_minimum_value:
      name: Minimum value
      description:
        The optional minimum value the selected values should not go below
      example: 0.10
      selector:
        number:
          step: any
          mode: box
    target_maximum_value:
      name: Maximum value
      description:
        The optional maximum value the selected values should not go above
      example: 0.10
      selector:
        number:
          step: any
          mode: box
    target_weighting:
      name: Weighting
      description:
        The optional weighting that should be applied to the selected values
      example: '1,2,1'
      selector:
        text:
    persist_changes:
      name: Persist Changes
      description: Determines if the changes should be persisted to the original configuration or should be temporary and reset upon integration reload.
      selector:
        boolean:

update_target_timeframe_data_source:
  name: Update target timeframe data source
  description: Updates the source data for a given targetframe period. This will replace any existing data for the source.
  target:
    entity:
      integration: target_timeframes
      domain: sensor
  fields:
    data:
      name: Data
      description: The collection of data to update.
      example: >-
        [
          {
            "start": "2025-01-01T00:00:00Z",
            "end": "2025-01-01T00:30:00Z",
            "value": 0.1,
            "metadata": {
              // Any additional metadata that might describe how the value was created
            }
          }
        ]
      selector:
        object: